APT::FTPArchive::Release {
    Origin "OxyohanOS";
    Label "OxyohanOS";
    Suite "stable";
    Codename "stable";
    Architectures "amd64";
    Components "main";
    Description "Repositorio APT do OxyohanOS";
};